site_name:  bpmn-server
doc_dir: docs
site_dir: .
theme:
  name: readthedocs
use_directory_urls: true
markdown_extensions:
  - toc:
      permalink: "#"
nav:  
- Overview:  index.md
- 'Invoking Workflows': invokation.md 
- 'Execution': execution.md
- 'Scripting': scripting.md
- 'Security': security.md
- 'Data': data.md 
- 'Examples': examples.md 
- 'API Summary': api-summary.md
- 'API': api/readme.md
- 'Setup': setup.md 
- 'Application Integration': customization.md 